// Generated by CoffeeScript 1.7.1
var Item;

Item = (function() {
  function Item(id, title, desc, price) {
    this.id = id;
    this.title = title;
    this.desc = desc;
    this.price = price;
  }

  return Item;

})();

//# sourceMappingURL=Item.map
